@startuml

package Model #feb40f {
class "Agendamento" as ag {
+CpfDoPaciente
+DataDaConsulta
+HoraInicial
+HoraFinal
}
class agb as "AgendamentoBuilder"{
Valida dados de Agendamento
}
class pc as "Paciente" {
+Cpf
+Nome
+DataDeNascimento
}
class pcb as "  PacienteBuilder  " {
Valida dados de Paciente
}
}

package Controller #7FFF00 {

class "AgendamentoController" as agc {
Recebe os dados de AgendamentoView e os envia para 
função correspondente na camada de Dados 
+AgendarConsulta()
+CancelarConsulta()
+GetAgendamentos()
}
class pcc as "PacienteController" {
Recebe os dados de PacienteView e os envia para 
função correspondente na camada de Dados 
+IncluirPaciente()
+ExcluirPaciente()
+GetPacientes()
}
}

package View #D84437 {

class "PacienteView" as pv {
Interage com o usuário para realizar as 
funcionalidades referentes a classe Paciente
+CadastrarPaciente()
+ExcluirPaciente()
+ListarPacientesPorCpf()
+ListarPacientesPorNome()
}

class "AgendamentoView" as av {
Interage com o usuário para realizar as 
funcionalidades referentes a classe Agendamento
+AgendarConsulta()
+CancelarAgendamento()
+ListarAgendaInteira()
+ListarAgendaParcial()
}

class "UserInterface" as ui {
Interage com o usuário por meio do console
+Start()
}
}

package Data #F9E4BC {

interface "IConsultorio" as ic{
Métodos Públicos para a manipulação dos Dados (Agendamentos e Pacientes)

        +AddPaciente(Paciente): bool

        +DeletePaciente(Paciente): bool

        +GetAllPacientes(): IEnumerable<Paciente> 

        +AddAgendamento(Agendamento): bool

        +DeleteAgendamento(ulong, DateTime, ushort): bool

        +GetAllAgendamentos(): IEnumerable<Agendamento> 

        +CpfExists(ulong): bool

        +GetPacienteByCpf(ulong): Paciente 

        +DeleteAllAgendamentosFromPaciente(Paciente): bool

        +IsAgendamentoCadastrado(Agendamento): bool
}

class "PacienteDao" as pd {
Responsável pelo acesso aos dados dos Pacientes
+Add()
+Delete()
+GetAll()
}
class "AgendamentoDao" as ad {
Responsável pelo acesso aos dados dos Agendamentos
+Add()
+Delete()
+GetAll()
}

package Entity {

class "EntityConsultorio" as ce {
}
class "EntityContext" as cc {
Implementa a persistência pelo framework Entity
} 
}

package NonPersistent {

class "DefaultConsultorio" as dc {
}

class "DefaultContext" as dcc {
objeto Singleton que mantém o contexto dos dados.
**É necessário para que PacienteDao e AgendamentoDao
tenham acesso aos mesmos dados**
}

}

pcb o-down- pc
agb o-down- ag

ui *-down- av
ui *-down- pv

pcc *-- pd
agc *-- ad

dcc "1" *-- "n" pc
dcc "1" *-- "n" ag
cc "1" *-- "n" pc
cc "1" *-- "n" ag

pv *-- pcc
av *-- agc


pv *--  pcb
av *-- agb

pd *-- ic
ad *-- ic

ic <-- dc
ic <-- ce

ce *-- cc
dc *-- dcc

@enduml